### ISSUE TITLE
Talon ID cannot be 99

### ISSUE THREAD

**Issue by ozrien** [KSHS-Robotics-Club/BasicFRCJava#1]
https://github.com/KSHS-Robotics-Club/BasicFRCJava/blob/f22c4f2640d164c2cebc4a6eb853c8b4cc8164b6/src/main/java/frc/robot/Robot.java#L29C19-L29C26

Talon ID must be within [0,62].  Tuner X also does not let you set it to 99.

**Comment by spacey-sooty** [comment]
I know we don't have a robot at this point so I have it set to 99 so people know it needs to be updated
